# ============================================================
# advanced/04-design-patterns/exercises/01-easy.py
# Topic: Design Patterns — Singleton, Factory, Template Method
# Difficulty: Easy
# ============================================================

# Exercise 1 — Singleton: Application Config
# -------------------------------------------
# Implement a Singleton class AppConfig that:
#   - Stores settings in a dict: {"debug": False, "log_level": "INFO", "version": "1.0"}
#   - Has a get(key) method → returns the value for key
#   - Has a set(key, value) method → updates a setting
#   - Guarantees that all callers share the same instance
#
# Expected:
#   a = AppConfig()
#   b = AppConfig()
#   a is b             → True
#   a.set("debug", True)
#   b.get("debug")     → True   (same instance, changes are shared)

# Write your code here


# Exercise 2 — Factory: Shape creator
# ------------------------------------
# Create a shape factory function create_shape(shape_type, **kwargs)
# that creates and returns a shape object given a type string.
# Supported types: "circle" (radius), "rectangle" (width, height),
#                  "triangle" (base, height)
# Each shape class must have an area() method and a __str__.
# Raise ValueError for unknown types.
#
# Expected:
#   c = create_shape("circle", radius=5)
#   r = create_shape("rectangle", width=4, height=6)
#   t = create_shape("triangle", base=3, height=8)
#   print(c.area())   → 78.53975
#   print(r.area())   → 24
#   print(t.area())   → 12.0
#   create_shape("hexagon")  → ValueError

# Write your code here


# Exercise 3 — Template Method: Report generator
# -----------------------------------------------
# Build a report generator using the Template Method pattern.
# Base class Report has a generate() method that calls in order:
#   1. header()     → returns a string (header line)
#   2. body()       → returns a string (main content)
#   3. footer()     → returns a string (footer line)
# generate() concatenates and prints all three.
#
# Create two subclasses:
#   HTMLReport   — wraps output in <html><body> tags
#   TextReport   — uses plain ASCII separators (===)
#
# Both share the same generate() template.
#
# Expected:
#   HTMLReport("Sales Q1").generate()
#   → <html><body>
#      <h1>Sales Q1</h1>
#      ... body content ...
#      <footer>Generated by HTMLReport</footer>
#      </body></html>
#
#   TextReport("Sales Q1").generate()
#   → ==================
#      Sales Q1
#      ==================
#      ... body ...
#      Generated by TextReport

# Write your code here
