# ============================================================
# advanced/04-design-patterns/solutions/01-easy-solution.py
# ============================================================

import math

# ----------------------------------------------------------
# Exercise 1 — Singleton: AppConfig
# ----------------------------------------------------------
class AppConfig:
    _instance = None

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super().__new__(cls)
            cls._instance._settings = {
                "debug": False,
                "log_level": "INFO",
                "version": "1.0",
            }
        return cls._instance

    def get(self, key):
        return self._settings[key]

    def set(self, key, value):
        self._settings[key] = value

a = AppConfig()
b = AppConfig()
print(a is b)           # True
a.set("debug", True)
print(b.get("debug"))   # True — same instance


# ----------------------------------------------------------
# Exercise 2 — Factory: Shape creator
# ----------------------------------------------------------
class Circle:
    def __init__(self, radius):
        self.radius = radius

    def area(self):
        return round(math.pi * self.radius ** 2, 5)

    def __str__(self):
        return f"Circle(radius={self.radius})"

class Rectangle:
    def __init__(self, width, height):
        self.width  = width
        self.height = height

    def area(self):
        return self.width * self.height

    def __str__(self):
        return f"Rectangle(width={self.width}, height={self.height})"

class Triangle:
    def __init__(self, base, height):
        self.base   = base
        self.height = height

    def area(self):
        return 0.5 * self.base * self.height

    def __str__(self):
        return f"Triangle(base={self.base}, height={self.height})"


_SHAPES = {"circle": Circle, "rectangle": Rectangle, "triangle": Triangle}

def create_shape(shape_type, **kwargs):
    cls = _SHAPES.get(shape_type.lower())
    if cls is None:
        raise ValueError(f"Unknown shape: {shape_type!r}. Choose: {list(_SHAPES)}")
    return cls(**kwargs)


c = create_shape("circle", radius=5)
r = create_shape("rectangle", width=4, height=6)
t = create_shape("triangle", base=3, height=8)
print(c, c.area())   # Circle(radius=5) 78.53975
print(r, r.area())   # Rectangle(width=4, height=6) 24
print(t, t.area())   # Triangle(base=3, height=8) 12.0

try:
    create_shape("hexagon")
except ValueError as e:
    print(e)


# ----------------------------------------------------------
# Exercise 3 — Template Method: Report generator
# ----------------------------------------------------------
class Report:
    def __init__(self, title):
        self.title = title

    def header(self):
        raise NotImplementedError

    def body(self):
        return f"Report content for: {self.title}"

    def footer(self):
        raise NotImplementedError

    def generate(self):
        print(self.header())
        print(self.body())
        print(self.footer())
        print()


class HTMLReport(Report):
    def header(self):
        return f"<html><body>\n<h1>{self.title}</h1>"

    def footer(self):
        return f"<footer>Generated by HTMLReport</footer>\n</body></html>"


class TextReport(Report):
    def header(self):
        sep = "=" * max(20, len(self.title) + 4)
        return f"{sep}\n{self.title}\n{sep}"

    def footer(self):
        return f"Generated by TextReport"


print("--- HTMLReport ---")
HTMLReport("Sales Q1").generate()

print("--- TextReport ---")
TextReport("Sales Q1").generate()
